### ISSUE TITLE
Edge dragging breaks when disconnected twice

### ISSUE THREAD

**Issue by daniel0611** [PalladioSimulator/Palladio-Supporting-DataFlowConfidentiality-WebBasedEditor#2]
Currently, the edge editing for edges breaks when disconnecting edges and leaving them dangling without a source or target node twice.
This is caused by sprotty creating a dangling element connected to the edge. When leaving the edge danging the second time it fails to generate this pseudo-element again because it still exists and was not removed.

This was found by @sebinside.
The underlying problem of this is inside the sprotty edge edit implementation which has this bug since the 0.13.0 release. This has been fixed with https://github.com/eclipse-sprotty/sprotty/pull/337. This fix has not yet been released, however.

Our options:
- Wait for a new sprotty release to be published with the fix
- Use the latest sprotty dev version from the `master` branch. This requires building sprotty alongside our project.
- Downgrade sprotty to 0.12.0

Downgrading isn't feasible because 0.13.0 introduced support for drop events in mouse listeners which we currently use to create new nodes. Using the sprotty dev version is hard because it would require separate checkout for the sprotty repo, building it and linking it using `npm link` which makes setup significantly harder. Because of this, I would prefer to just live with this bug for now and wait for the fix to be included in a published version.

**Comment by sebinside** [comment]
Do have any information about the ETA of the next sprotty release? Nevertheless, I would also prefer the solution of ignoring the bug for now. Thank you for the investigation!

**Comment by daniel0611** [comment]
There are no official ETAs about releases as far as I know but in the past there always was a release about every 5-7 months. The latest release is from dec 2022 so I would assume it will happen rather recently. No guarantees tho.
